services:
  postgres-mutants:
    container_name: MUTANTS
    image: postgres
    environment:
      POSTGRES_USER: cerebro
      POSTGRES_PASSWORD: cerebro
      POSTGRES_DB: mutants_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres-humans:
    container_name: HUMANS
    image: postgres
    environment:
      POSTGRES_USER: cerebro
      POSTGRES_PASSWORD: cerebro
      POSTGRES_DB: humans_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: