services:
  postgres-mutants:
    container_name: Mutants
    image: postgres
    environment:
      POSTGRES_USER: cerebro
      POSTGRES_PASSWORD: cerebro
      POSTGRES_DB: mutants_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres-history:
    container_name: History
    image: postgres
    environment:
      POSTGRES_USER: cerebro
      POSTGRES_PASSWORD: cerebro
      POSTGRES_DB: history_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres-xgene:
    container_name: Xgene
    image: postgres
    environment:
      POSTGRES_USER: cerebro
      POSTGRES_PASSWORD: cerebro
      POSTGRES_DB: xgene_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5436:5432"
    networks:
      - postgres
    restart: unless-stopped

  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3.9.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: