server:
  port: 8888

spring:
  cloud:
    gateway:
      routes:
        - id: mutant
          uri: http://localhost:8080
          predicates:
            - Path=/mutants/**
          filters:
            - PrefixPath=/api
        - id: xgene
          uri: http://localhost:8082
          predicates:
            - Path=/xgene/**
          filters:
            - PrefixPath=/api
        - id: history
          uri: http://localhost:8081
          predicates:
            - Path=/histories/**
          filters:
            - PrefixPath=/api
        - id: threat
          uri: http://localhost:8088
          predicates:
            - Path=/threats/**
          filters:
            - PrefixPath=/api
