server:
  port: 8082

spring:
  application:
    name: xgene
  datasource:
    username: cerebro
    password: cerebro
    url: jdbc:postgresql://localhost:5436/xgene_db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
    show_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true