server:
  port: 8081

spring:
  application:
    name: human
  datasource:
    username: cerebro
    password: cerebro
    url: jdbc:postgresql://localhost:5432/humans_db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
    show_sql: true
